package klyx:extension;

world extension {
    import system;

    /// Initializes the extension.
    export init-extension: func();
    export uninstall: func();

    /// The type of a downloaded file.
    enum downloaded-file-type {
        /// A gzipped file (`.gz`).
        gzip,
        /// A gzipped tar archive (`.tar.gz`).
        gzip-tar,
        /// A ZIP file (`.zip`).
        zip,
        /// An uncompressed file.
        uncompressed,
    }

    /// Downloads a file from the given URL and saves it to the given path within the extension's
    /// working directory.
    ///
    /// The file will be extracted according to the given file type.
    import download-file: func(url: string, file-path: string, file-type: downloaded-file-type) -> result<_, string>;
}
